--- 
clone: 
  depth: 1
kind: pipeline
name: ReinaPipeline
steps: 
  - 
    commands: 
      - "bash komodo.sh"
    image: baalajimaestro/android_build:latest
    name: Zhard-Lair
    trigger: 
      branch: 
        - master
