--- 
clone: 
  depth: 1
kind: pipeline
name: ReinaPipeline
steps: 
  - 
    commands: 
      - "apt-get update && apt-get install git -y && bash komodo.sh"
    image: ubuntu:latest
    name: Zhard-Lair
    trigger: 
      branch: 
        - master
